[workspace]
authors = ["MessereN <nicholas.messere@torontomu.ca>"]
channels = ["conda-forge"]
name = "write_from_sheet_to_db"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]
start = "python scripts/conversion.py"

[dependencies]
python = ">=3.14.2,<3.15"
python-dotenv = ">=1.2.1,<2"
gspread = ">=5.12.4,<6"
google-auth = ">=2.47.0,<3"
pymongo = ">=4.16.0,<5"
